#version: "3.9"
#
#services:
##  authorization:
##     container_name: authorization
##     image: authorization:latest
##     build:
##         context: .
##         dockerfile: ./src/Authorization/Authorization.API/Dockerfile
##     # depends_on:
##     #    - seq
##     #    - redis
##     ports:
##        - 2000:80
##     restart: always
##     networks:
##        - revereseproxy-network
##
##  apigateway:
##     container_name: apigateway
##     image: apigateway:latest
##     build:
##         context: .
##         dockerfile: ./src/ReverseProxy/ApiGateway/Dockerfile
##     # depends_on:
##     #    - seq
##     #    - redis
##     ports:
##         - 5000:80
##     restart: always
##     networks:
##         - revereseproxy-network
#
##  command:
##      container_name: command
##      image: command:latest
##      build:
##          context: .
##          dockerfile: ./src/DistributedSystem.API/Dockerfile
##      # depends_on:
##      #    - seq
##      #    - redis
##      ports:
##          - 3000:80
##      restart: always
##      networks:
##          - revereseproxy-network
#
##  query:
##      container_name: query
##      image: query:latest
##      build:
##          context: .
##          dockerfile: ./src/Query/Query.API/Dockerfile
##      # depends_on:
##      #    - seq
##      #    - redis
##      ports:
##          - 4000:80
##      restart: always
##      networks:
##          - revereseproxy-network
#
#networks:
#  revereseproxy-network: